 // ✅ Words to ignore (too generic or too broad)
  export const ignoreWords = [
    // 🌍 General
    "nigeria",
    "federal republic of nigeria",
    "naija",

    // 🏙️ Major Nigerian cities
    "lag",
    "lagos",
    "abuja",
    "port harcourt",
    "ph",
    "phc",
    "kano",
    "ibadan",
    "benin",
    "enugu",
    "kaduna",
    "jos",
    "maiduguri",
    "owerri",
    "uyo",
    "ilorin",
    "abeokuta",
    "asaba",
    "onitsha",
    "warri",

    // 🧭 All Nigerian states
    "abia",
    "adamawa",
    "akwa ibom",
    "anambra",
    "bauchi",
    "bayelsa",
    "benue",
    "borno",
    "cross river",
    "delta",
    "ebonyi",
    "edo",
    "ekiti",
    "enugu",
    "gombe",
    "imo",
    "jigawa",
    "kaduna",
    "kano",
    "katsina",
    "kebbi",
    "kogi",
    "kwara",
    "lagos",
    "nasarawa",
    "niger",
    "ogun",
    "ondo",
    "osun",
    "oyo",
    "plateau",
    "rivers",
    "sokoto",
    "taraba",
    "yobe",
    "zamfara",
    "fct",
    "f.c.t",
  ];