/**
 * PREFERENCE FEATURE CONFIGURATIONS
 * Copy this file to: src/data/preference-configs.ts
 * Contains all amenities, features, and budget thresholds
 */

import { FeatureConfig, BudgetThreshold } from "@/types/preference-form";

// Feature configurations with budget requirements - Memoized static data
export const FEATURE_CONFIGS: Record<string, FeatureConfig> = {
  "buy-residential": {
    basic: [
      { name: "Kitchenette", type: "basic" },
      { name: "Security Cameras", type: "basic" },
      { name: "Children Playground", type: "basic" },
      { name: "Open Floor Plan", type: "basic" },
      { name: "Walk-in Closet", type: "basic" },
      { name: "WiFi", type: "basic" },
      { name: "Library", type: "basic" },
      { name: "Home Office", type: "basic" },
      { name: "Bathtub", type: "basic" },
      { name: "Garage", type: "basic" },
      { name: "Staff Room", type: "basic" },
      { name: "Pantry", type: "basic" },
      { name: "Built-in Cupboards", type: "basic" },
      { name: "Security Post", type: "basic" },
      { name: "Access Gate", type: "basic" },
      { name: "Air Conditioner", type: "basic" },
      { name: "Wheelchair Friendly", type: "basic" },
      { name: "Garden", type: "basic" },
    ],
    premium: [
      { name: "Gym House", type: "premium" },
      { name: "Swimming Pool", type: "premium" },
      { name: "Outdoor Kitchen", type: "premium" },
      { name: "Rooftops", type: "premium" },
      { name: "In-house Cinema", type: "premium" },
      { name: "Tennis Court", type: "premium" },
      { name: "Elevator", type: "premium" },
      { name: "Electric Fencing", type: "premium" },
      { name: "Inverter", type: "premium" },
      { name: "Sea View", type: "premium" },
      { name: "Jacuzzi", type: "premium" },
    ],
  },
  "buy-commercial": {
    basic: [
      { name: "Power Supply", type: "basic" },
      { name: "Water Supply", type: "basic" },
      { name: "Air Conditioning", type: "basic" },
      { name: "Parking Space", type: "basic" },
      { name: "Security", type: "basic" },
      { name: "Internet (Wi-Fi)", type: "basic" },
      { name: "Reception Area", type: "basic" },
      { name: "Elevator", type: "basic" },
      { name: "Standby Generator", type: "basic" },
    ],
    premium: [
      { name: "Central Cooling System", type: "premium" },
      { name: "Fire Safety Equipment", type: "premium" },
      { name: "Industrial Lift", type: "premium" },
      { name: "CCTV Monitoring System", type: "premium" },
      { name: "Conference Room", type: "premium" },
      { name: "Fiber Optic Internet", type: "premium" },
      { name: "Backup Solar/Inverter", type: "premium" },
      { name: "Loading Dock", type: "premium" },
      { name: "Smart Building Automation", type: "premium" },
    ],
  },
  "buy-land": {
    basic: [],
    premium: [],
  },
  "rent-residential": {
    basic: [
      { name: "Kitchenette", type: "basic" },
      { name: "Security Cameras", type: "basic" },
      { name: "Children Playground", type: "basic" },
      { name: "Open Floor Plan", type: "basic" },
      { name: "Walk-in Closet", type: "basic" },
      { name: "WiFi", type: "basic" },
      { name: "Library", type: "basic" },
      { name: "Home Office", type: "basic" },
      { name: "Bathtub", type: "basic" },
      { name: "Garage", type: "basic" },
      { name: "Staff Room", type: "basic" },
      { name: "Pantry", type: "basic" },
      { name: "Built-in Cupboards", type: "basic" },
      { name: "Security Post", type: "basic" },
      { name: "Access Gate", type: "basic" },
      { name: "Air Conditioner", type: "basic" },
      { name: "Wheelchair Friendly", type: "basic" },
      { name: "Garden", type: "basic" },
    ],
    premium: [
      { name: "Gym House", type: "premium" },
      { name: "Swimming Pool", type: "premium" },
      { name: "Outdoor Kitchen", type: "premium" },
      { name: "Rooftops", type: "premium" },
      { name: "In-house Cinema", type: "premium" },
      { name: "Tennis Court", type: "premium" },
      { name: "Elevator", type: "premium" },
      { name: "Electric Fencing", type: "premium" },
      { name: "Inverter", type: "premium" },
      { name: "Sea View", type: "premium" },
      { name: "Jacuzzi", type: "premium" },
    ],
  },
  "rent-commercial": {
    basic: [
      { name: "Power Supply", type: "basic" },
      { name: "Water Supply", type: "basic" },
      { name: "Air Conditioning", type: "basic" },
      { name: "Parking Space", type: "basic" },
      { name: "Security", type: "basic" },
      { name: "Internet (Wi-Fi)", type: "basic" },
      { name: "Reception Area", type: "basic" },
      { name: "Elevator", type: "basic" },
      { name: "Standby Generator", type: "basic" },
    ],
    premium: [
      { name: "Central Cooling System", type: "premium" },
      { name: "Fire Safety Equipment", type: "premium" },
      { name: "Industrial Lift", type: "premium" },
      { name: "CCTV Monitoring System", type: "premium" },
      { name: "Conference Room", type: "premium" },
      { name: "Fiber Optic Internet", type: "premium" },
      { name: "Backup Solar/Inverter", type: "premium" },
      { name: "Loading Dock", type: "premium" },
      { name: "Smart Building Automation", type: "premium" },
    ],
  },
  "rent-land": {
    basic: [],
    premium: [],
  },
  "joint-venture-residential": {
    basic: [
      { name: "Kitchenette", type: "basic" },
      { name: "Security Cameras", type: "basic" },
      { name: "Children Playground", type: "basic" },
      { name: "Open Floor Plan", type: "basic" },
      { name: "Walk-in Closet", type: "basic" },
      { name: "WiFi", type: "basic" },
      { name: "Library", type: "basic" },
      { name: "Home Office", type: "basic" },
      { name: "Bathtub", type: "basic" },
      { name: "Garage", type: "basic" },
      { name: "Staff Room", type: "basic" },
      { name: "Pantry", type: "basic" },
      { name: "Built-in Cupboards", type: "basic" },
      { name: "Security Post", type: "basic" },
      { name: "Access Gate", type: "basic" },
      { name: "Air Conditioner", type: "basic" },
      { name: "Wheelchair Friendly", type: "basic" },
      { name: "Garden", type: "basic" },
    ],
    premium: [
      { name: "Gym House", type: "premium" },
      { name: "Swimming Pool", type: "premium" },
      { name: "Outdoor Kitchen", type: "premium" },
      { name: "Rooftops", type: "premium" },
      { name: "In-house Cinema", type: "premium" },
      { name: "Tennis Court", type: "premium" },
      { name: "Elevator", type: "premium" },
      { name: "Electric Fencing", type: "premium" },
      { name: "Inverter", type: "premium" },
      { name: "Sea View", type: "premium" },
      { name: "Jacuzzi", type: "premium" },
    ],
  },
  "joint-venture-commercial": {
    basic: [
      { name: "Power Supply", type: "basic" },
      { name: "Water Supply", type: "basic" },
      { name: "Air Conditioning", type: "basic" },
      { name: "Parking Space", type: "basic" },
      { name: "Security", type: "basic" },
      { name: "Internet (Wi-Fi)", type: "basic" },
      { name: "Reception Area", type: "basic" },
      { name: "Elevator", type: "basic" },
      { name: "Standby Generator", type: "basic" },
    ],
    premium: [
      { name: "Central Cooling System", type: "premium" },
      { name: "Fire Safety Equipment", type: "premium" },
      { name: "Industrial Lift", type: "premium" },
      { name: "CCTV Monitoring System", type: "premium" },
      { name: "Conference Room", type: "premium" },
      { name: "Fiber Optic Internet", type: "premium" },
      { name: "Backup Solar/Inverter", type: "premium" },
      { name: "Loading Dock", type: "premium" },
      { name: "Smart Building Automation", type: "premium" },
    ],
  },
  "joint-venture-land": {
    basic: [],
    premium: [],
  },
  shortlet: {
    basic: [
      { name: "Wi-Fi", type: "basic" },
      { name: "Air Conditioning", type: "basic" },
      { name: "Power Supply", type: "basic" },
      { name: "Security", type: "basic" },
      { name: "Parking", type: "basic" },
      { name: "Clean Water", type: "basic" },
      { name: "Kitchen", type: "basic" },
      { name: "Clean Bathroom", type: "basic" },
    ],
    comfort: [
      { name: "Laundry", type: "comfort" },
      { name: "Smart TV / Netflix", type: "comfort" },
      { name: "Balcony", type: "comfort" },
      { name: "Housekeeping", type: "comfort" },
      { name: "Breakfast Included", type: "comfort" },
      { name: "Private Entrance", type: "comfort" },
      { name: "POP Ceiling", type: "comfort" },
      { name: "Access Gate", type: "comfort" },
    ],
    premium: [
      { name: "Gym Access", type: "premium" },
      { name: "Swimming Pool", type: "premium" },
      { name: "Inverter / Solar Backup", type: "premium" },
      { name: "Rooftop Lounge", type: "premium" },
      { name: "Jacuzzi", type: "premium" },
      { name: "Sea View", type: "premium" },
      { name: "Pet-Friendly", type: "premium" },
      { name: "Outdoor Kitchen", type: "premium" },
      { name: "Smart Lock", type: "premium" },
      { name: "Close to Major Attractions", type: "premium" },
    ],
  },
};

// Budget thresholds by location and listing type - Memoized static data
export const DEFAULT_BUDGET_THRESHOLDS: BudgetThreshold[] = [
  // Lagos thresholds
  { location: "Lagos", listingType: "buy", minAmount: 5000000 },
  { location: "Lagos", listingType: "rent", minAmount: 200000 },
  { location: "Lagos", listingType: "joint-venture", minAmount: 10000000 },
  { location: "Lagos", listingType: "shortlet", minAmount: 15000 },

  // Abuja thresholds
  { location: "Abuja", listingType: "buy", minAmount: 8000000 },
  { location: "Abuja", listingType: "rent", minAmount: 300000 },
  { location: "Abuja", listingType: "joint-venture", minAmount: 15000000 },
  { location: "Abuja", listingType: "shortlet", minAmount: 25000 },

  // Default thresholds for other locations
  { location: "default", listingType: "buy", minAmount: 2000000 },
  { location: "default", listingType: "rent", minAmount: 100000 },
  { location: "default", listingType: "joint-venture", minAmount: 5000000 },
  { location: "default", listingType: "shortlet", minAmount: 10000 },
];
